server:
  port: 9000
#  servlet:
#    context-path: /springboot
# MC 账套  192.168.1.114 AIS20161208122115
# SY 账套 192.168.1.112 AIS20161208124844
#VG账套 192.168.1.90 AIS20180329095510

spring:
  datasource:
    dynamic:
      primary: master #1默认麻涌正式数据库  AIS20161208122115   //AIS20180703164607 培训 实操
      datasource:
        master: #MC正式数据库
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          #schema: classpath:db/schema-h2.sql
          #data: classpath:db/data-h2.sql
          url: jdbc:sqlserver://192.168.1.114:1433;database=AIS20161208122115;integratedSecurity=false
          username: sa
          password: 请修改
        db1: #SY正式数据库AIS20161208124844  
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver        
          url: jdbc:sqlserver://192.168.1.112:1433;database=AIS20161208124844;integratedSecurity=false
          username: sa
          password: 请修改
        db2: #VG正式数据库
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver        
          url: jdbc:sqlserver://192.168.1.90:1433;database=AIS20180329095510;integratedSecurity=false
          username: sa
          password: 请修改
          
  freemarker:
    request-context-attribute: request
    #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
#mybatis
mybatis-plus:
#  mapper-locations: classpath*:/mapper/*.xml
  
  mapper-locations: classpath*:mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.vg.kd.entity
  #typeEnumsPackage: com.vg.kd.entity.entity.enums
  global-config:
    # 数据库相关配置
    #sql-parser-cache: true
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not-empty
      #驼峰下划线转换
      column-underline: false #true  
      #数据库大写下划线转换
      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: sql-server
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
 
  
logging:
  level:
     com.vg.kd.mapper : debug
     